# Generated by Django 2.1.7 on 2019-04-07 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_authenticated'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthen',
            fields=[
                ('id_User', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.User', unique=True)),
                ('token', models.CharField(max_length=100)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_authenticated',
        ),
    ]
