# Generated by Django 2.1.7 on 2019-04-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190408_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauthen',
            old_name='id_User',
            new_name='user',
        ),
    ]
