# Generated by Django 2.1.7 on 2019-04-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190408_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthen',
            name='token',
            field=models.CharField(max_length=300),
        ),
    ]
