# Generated by Django 2.1.7 on 2019-04-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190410_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.AutoField(null=None, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('user', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
